name: Build Service
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-port:
        required: true
        type: number
    secrets:
      REGISTRY_TOKEN:
        required: true
      REMOTE_HOST:
        required: true
      REMOTE_USER:
        required: true
      REMOTE_KEY:
        required: true

jobs:
  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    steps:
      - id: repository
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - uses: actions/checkout@v4

      - name: Connect to remote server
        uses: appleboy/ssh-action@v1.0.3
        env:
          USER_REGISTRY: ${{ github.actor }}
          PASS_REGISTRY: ${{ secrets.REGISTRY_TOKEN }}
          ACTION_REGISTRY: ${{ steps.repository.outputs.lowercase }}
          PORT: ${{ inputs.service-port }}
          SERVICE_NAME: ${{ inputs.service-name }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          envs: USER_REGISTRY,PASS_REGISTRY,ACTION_REGISTRY,PORT,SERVICE_NAME
          script_stop: true
          script: |
            docker login ghcr.io -u $USER_REGISTRY --password $PASS_REGISTRY 
            docker pull ghcr.io/$ACTION_REGISTRY/$SERVICE_NAME:latest
            (docker stop $SERVICE_NAME && docker rm $SERVICE_NAME || true)
            docker run -d -p $PORT:$PORT --name $SERVICE_NAME --env-file $SERVICE_NAME.env --restart=always ghcr.io/$ACTION_REGISTRY/$SERVICE_NAME:latest
